# Generated by Django 2.2.3 on 2019-07-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_at', models.DateTimeField(verbose_name='Дата и время отправки')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщение')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('send_count', models.IntegerField(default=0, verbose_name='Количество отправлений')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MessageButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Кнопка')),
                ('text', models.TextField(verbose_name='Текст письма')),
                ('click_count', models.IntegerField(default=0, verbose_name='Количество нажатий')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buttonsbot.Message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
            },
        ),
    ]
