# Generated by Django 2.2.3 on 2019-07-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buttonsbot', '0003_message_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagebutton',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagebutton',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='send_now',
            field=models.BooleanField(default=0, verbose_name='Отправить сразу'),
        ),
        migrations.AddField(
            model_name='messagebutton',
            name='child_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_message', to='buttonsbot.Message', verbose_name='Письмо'),
        ),
        migrations.AddField(
            model_name='messagebutton',
            name='parent_message',
            field=models.ManyToManyField(related_name='parent_message', to='buttonsbot.Message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='Идентификатор чата')),
                ('notification_count', models.IntegerField(default=0, verbose_name='Уведомлен раз')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Пользователь заблокирован')),
                ('last_pressed_button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buttonsbot.MessageButton', verbose_name='Нажатая кнопка')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
    ]
