# Generated by Django 2.2.3 on 2019-07-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buttonsbot', '0004_auto_20190712_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='send_count',
        ),
        migrations.AlterField(
            model_name='messagebutton',
            name='child_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_message', to='buttonsbot.Message', verbose_name='Письмо при нажатии на кнопку'),
        ),
    ]
