# Generated by Django 2.2.3 on 2019-07-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttonsbot', '0005_auto_20190712_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagebutton',
            name='parent_message',
        ),
        migrations.AddField(
            model_name='message',
            name='buttons',
            field=models.ManyToManyField(to='buttonsbot.MessageButton', verbose_name='Кнопки'),
        ),
    ]
