# Generated by Django 2.2.3 on 2019-07-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buttonsbot', '0006_auto_20190712_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='buttons',
            field=models.ManyToManyField(blank=True, to='buttonsbot.MessageButton', verbose_name='Кнопки'),
        ),
        migrations.AlterField(
            model_name='messagebutton',
            name='child_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buttonsbot.Message', verbose_name='Письмо при нажатии на кнопку'),
        ),
    ]
