# Generated by Django 2.2.3 on 2019-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttonsbot', '0007_auto_20190712_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
