# Generated by Django 2.2.3 on 2019-07-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttonsbot', '0008_botusers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='message_images/', verbose_name='Картинка'),
        ),
    ]
